fix [BUG]: 日志中不应出现颜色 #113
DuckDuckStudio/Fufu_Tools pull request #114
Opened 2024-09-16 11:35 UTC by DuckDuckStudio

### 检查清单
- [x] 有链接Issue吗? -- Resolve #113 
- [x] 你检查过没有其他重复的 [拉取请求](https://github.com/DuckDuckStudio/Fufu_Tools/pulls)吗?
- [x] 此拉取请求仅针对一个问题/功能吗?
- [ ] 你在本地验证过你的修改吗?
- [x] 你确定你的描述足以让开发人员理解你的意图以及解决方案?

### 修改说明

@fjwxzde run test

---

2024-09-16 11:38 UTC, fjwxzde commented
Code QL ERROR:
> Error: The operation was canceled.

2024-09-16 11:39 UTC, DuckDuckStudio commented
@fjwxzde set

2024-09-16 11:40 UTC, fjwxzde commented
@fjwxzde run test

2024-09-16 11:43 UTC, fjwxzde requested changes
验证：
不支持带空格路径

2024-09-16 12:11 UTC, fjwxzde requested changes
Traceback (most recent call last):
  File "D:\...\Fufu_Tools\Tools\【实验性工具】\自动化\自动打包所有py文件\使用Nuitka.py", line 156, in <module>
    failed_file = package_py(file_path)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "D:\...\Fufu_Tools\Tools\【实验性工具】\自动化\自动打包所有py文件\使用Nuitka.py", line 101, in package_py
    fail += 1
    ^^^^
UnboundLocalError: cannot access local variable 'fail' where it is not associated with a value

2024-09-16 12:24 UTC, fjwxzde commented on Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
@Luna-Grace 
需要复核

```
raise WindowsError(
OSError: [Errno 123] getWindowsLongPathName for d:\\java\jdk-21\bin\api-ms-win-crt-runtime-l1-1-0.dll (文件名、目录名或 卷标语法不正确。)
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug
Nuitka-Reports: report.
打包 D:\....py 时出错:
Command 'python -m nuitka --output-dir="D:\..." --show-progress --windows-icon-from-ico="D:\...\ico.ico" --onefile --remove-output --clang "D:\....py"' returned non-zero exit status 1.
```

2024-09-16 12:38 UTC, Luna-Grace commented
> ~~好一个西红柿炒鸡蛋...~~

不同的错误：
```
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/lib/../lib/crt2u.o: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/crtbegin.o: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lm: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingw32: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc_eh: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmoldname: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwex: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lkernel32: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpthread: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ladvapi32: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lshell32: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -luser32: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lkernel32: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingw32: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc_eh: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmoldname: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmingwex: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lkernel32: No such file or directory
C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:/Users/.../AppData/Local/Nuitka/Nuitka/Cache/downloads/gcc/x86_64/13.2.0-16.0.6-11.0.1-msvcrt-r1/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/crtend.o: No such file or directory
collect2.exe: error: ld returned 1 exit status

scons: *** [D:\...\CODEDE~1\FUFU_D~1\--B15D~1\8356~1.DIS\_nuitka_temp.exe] Error 1
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
打包 D:\...\***.py 时出错:
Command 'python -m nuitka --output-dir="D:\..." --show-progress --windows-icon-from-ico="D:\...\ico.ico" --onefile --remove-output --mingw64 "D:\...\***.py"' returned non-zero exit status 1.
```

2024-09-16 14:07 UTC, DuckDuckStudio commented
这两个似乎都是编译器的问题，而不是我的程序的问题。

2024-09-17 03:04 UTC, DuckDuckStudio commented
要不先合并吧，被编译错误一直卡在这里也不是办法...而且也不像是程序的问题

2024-09-17 04:14 UTC, DuckDuckStudio commented
@Luna-Grace 没意见的话先合了

2024-09-26 09:52 UTC, fjwxzde approved these changes

2024-09-28 01:37 UTC, DuckDuckStudio reviewed
@Luna-Grace 
应该不是我的程序的问题

2024-09-28 01:38 UTC, Luna-Grace approved these changes

2024-09-28 01:39 UTC, Luna-Grace commented
@DuckDuckStudio 
批了，你看看行不行，行就merge

2024-10-25 08:50 UTC, merged

2025-02-10 08:04 UTC, DuckDuckStudio commented
Tag: 区域-外部