[Develop branch merge request] Add Terminal command.
DuckDuckStudio/Fufu_Tools pull request #53
Opened 2024-06-03 15:34 UTC by Luna-Grace

给开发工具添加终端脚本

2024-06-03 15:35 UTC, DuckDuckStudio requested changes
请在README中标明如何使用。

2024-06-04 09:58 UTC, Luna-Grace commented
已在 提交[b95584f](https://github.com/DuckDuckStudio/yazicbs.github.io/commit/b95584f12422dfbd8c0b18ead42a62c3a825a860) 中补充文档。

2024-06-04 10:07 UTC, DuckDuckStudio requested changes
同时，还建议添加在主程序自动配置环境变量的功能

2024-06-04 10:07 UTC, DuckDuckStudio commented on Tools/开发工具/Script/ffdev.ps1
> +}
```suggestion
}

```
建议添加末尾空行

2024-06-04 10:07 UTC, DuckDuckStudio commented on Tools/开发工具/Script/ffdev.ps1
> +}
```suggestion
}

```
建议添加末尾空行

2024-06-04 10:07 UTC, DuckDuckStudio commented on Tools/开发工具/Script/提示.txt
> +    将本文件夹路径添加到系统PATH环境变量即可轻松使用`ffdev`参数调用开发工具！
```suggestion
    将本文件夹路径添加到系统PATH环境变量即可轻松使用`ffdev`参数调用开发工具！

```
建议添加末尾空行

2024-06-04 15:32 UTC, merged