[pref&fix] 优化休息一下的时间显示 & 更正自动打包py文件的路径
DuckDuckStudio/Fufu_Tools pull request #74
Opened 2024-06-27 13:28 UTC by DuckDuckStudio

[fix] 关于 #46 
@fjwxzde set

2024-06-27 13:30 UTC, fjwxzde commented on Tools/【实验性工具】/休息一下/休息一下.pyw
@Luna-Grace 需要手动测试

2024-06-28 10:27 UTC, DuckDuckStudio commented
@fjwxzde 指派

2024-06-28 10:40 UTC, Luna-Grace requested changes

2024-06-28 10:40 UTC, Luna-Grace commented on Tools/【实验性工具】/休息一下/休息一下.pyw
> +# 转单位
```suggestion
if total_seconds <= 0:
    ptint(f"{Fore.RED}错误{Fore.RESET} 设置的时间必须为正整数")
# 转单位
```

2024-06-28 10:43 UTC, DuckDuckStudio commented
对不起，我目前无法提交，晚些再试

2024-06-28 14:20 UTC, DuckDuckStudio commented
@fjwxzde run test

2024-06-28 14:27 UTC, fjwxzde commented
意外的`.0`
PS D:\...\Fufu_Tools> & d:/Duckhome/projects/MSVS/Source/Repos/Fufu_Tools/.venv/Scripts/python.exe d:/.../Fufu_Tools/test/单位.py
120.0个半 小时

2024-06-28 14:46 UTC, DuckDuckStudio commented
@fjwxzde run test

2024-06-28 14:48 UTC, fjwxzde requested changes

2024-06-28 14:48 UTC, fjwxzde commented on Tools/【实验性工具】/休息一下/休息一下.pyw
> +import math
```suggestion

```
多余导入

2024-06-28 14:50 UTC, DuckDuckStudio commented
@fjwxzde run test

2024-06-28 14:51 UTC, fjwxzde approved these changes

2024-06-28 14:59 UTC, Luna-Grace reviewed
@DuckDuckStudio 
你似乎忘记了将他移出`实验性工具`分类

2024-06-28 15:03 UTC, Luna-Grace approved these changes

2024-06-28 15:04 UTC, Luna-Grace commented
@fjwxzde run test

2024-06-28 15:05 UTC, fjwxzde approved these changes

2024-06-28 15:08 UTC, DuckDuckStudio commented
已更新文档

2024-06-28 15:09 UTC, merged